package ExceptionHandling;

public class CombinationTryCatchFinallyCase19 {

    public static void main(String[] args) {

/*        try {
            System.out.println("Try Outer");
            try {
                System.out.println("Try Inner");
            } catch (ArithmeticException e) {
                System.out.println(" Catch Inner");
            }
        }*/

        }
    }


//Invalid (outer catch block not present for outer try so exception
//Output: java: 'try' without 'catch', 'finally' or resource declarations
